// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/postlist": {
    params: {};
  };
  "/post/:postId": {
    params: {
      "postId": string;
    };
  };
  "/post/:postId/edit": {
    params: {
      "postId": string;
    };
  };
  "/makepost": {
    params: {};
  };
  "/editPassword": {
    params: {};
  };
  "/editProfile": {
    params: {};
  };
  "/notfound": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/postlist" | "/post/:postId" | "/post/:postId/edit" | "/makepost" | "/editPassword" | "/editProfile" | "/notfound" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/postlist.tsx": {
    id: "routes/postlist";
    page: "/postlist";
  };
  "routes/postDetail.tsx": {
    id: "routes/postDetail";
    page: "/post/:postId";
  };
  "routes/postEdit.tsx": {
    id: "routes/postEdit";
    page: "/post/:postId/edit";
  };
  "routes/makepost.tsx": {
    id: "routes/makepost";
    page: "/makepost";
  };
  "routes/editPassword.tsx": {
    id: "routes/editPassword";
    page: "/editPassword";
  };
  "routes/editProfile.tsx": {
    id: "routes/editProfile";
    page: "/editProfile";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/notfound";
  };
  "routes/access-block.tsx": {
    id: "routes/access-block";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/postlist": typeof import("./app/routes/postlist.tsx");
  "routes/postDetail": typeof import("./app/routes/postDetail.tsx");
  "routes/postEdit": typeof import("./app/routes/postEdit.tsx");
  "routes/makepost": typeof import("./app/routes/makepost.tsx");
  "routes/editPassword": typeof import("./app/routes/editPassword.tsx");
  "routes/editProfile": typeof import("./app/routes/editProfile.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
  "routes/access-block": typeof import("./app/routes/access-block.tsx");
};